### ISSUE TITLE
Model Weights

### ISSUE THREAD

**Issue by jerofad** [greentreeys/MIL-VT#5]
Where can we find this weight you specified in the code here?
It is not on the timm list of models. 
https://github.com/greentreeys/MIL-VT/blob/0b44e46bc02701901fc5462f19c1e2e50e5cd588/models/FinetuneVTmodels.py#L25

**Comment by YuboHe** [comment]
from models.MIL_VT import *

try add above code to train_APTOS_MIL-VT.py

**Comment by jerofad** [comment]
Yes tried that and still get the error. Stacktrace below

    Traceback (most recent call last):
      File "MIL-VT/train_APTOS_MIL-VT.py", line 437, in <module>
        main()
      File "MIL-VT/train_APTOS_MIL-VT.py", line 83, in main
        model = MIL_VT_FineTune(MODEL_PATH_finetune=MODEL_PATH_finetune, base_model=base_model, 
                        num_classes=n_classes)
      File "/mnt/qb/home/berens/jfadugba97/RetinaClassification/MIL-VT/models/FinetuneVTmodels.py", line 33, in 
               MIL_VT_FineTune drop_block_rate=None,
      File "/home/berens/jfadugba97/.conda/envs/retina/lib/python3.7/site-packages/timm/models/factory.py", line 67, in 
            create_model
       raise RuntimeError('Unknown model (%s)' % model_name)
    RuntimeError: Unknown model (MIL_VT_small_patch16_384)

**Comment by jerofad** [comment]
@YuboHe  have you ran this repository successfully ?

**Comment by YuboHe** [comment]
Yes,  I have ran it successfully  without error after I added the code I mentioned above. Before that, I have the same problem as yours. @jerofad

**Comment by liqiangde** [comment]
> 

hello, I had a similar error before. After adding that code, a new problem appeared. Do you know how to solve it?
Traceback (most recent call last):
  File "train_APTOS_MIL-VT.py", line 429, in <module>
    main()
  File "train_APTOS_MIL-VT.py", line 78, in main
    model = MIL_VT_FineTune(base_model, MODEL_PATH_finetune, num_classes=n_classes)
  File "/workspace/test/MIL-VT-main/models/FinetuneVTmodels.py", line 28, in MIL_VT_FineTune
    model = create_model(model_name=base_model,
  File "/opt/conda/envs/dual_learning/lib/python3.8/site-packages/timm/models/factory.py", line 71, in create_model
    model = create_fn(pretrained=pretrained, pretrained_cfg=pretrained_cfg, **kwargs)
  File "/workspace/test/MIL-VT-main/models/MIL_VT.py", line 216, in MIL_VT_small_patch16_512
    model = MILVisionTransformer(
  File "/workspace/test/MIL-VT-main/models/MIL_VT.py", line 13, in __init__
    super().__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'pretrained_cfg'

**Comment by liqiangde** [comment]
@jerofad 
hello, I had a similar error before. After adding that code, a new problem appeared. Do you know how to solve it?
Traceback (most recent call last):
File "train_APTOS_MIL-VT.py", line 429, in
main()
File "train_APTOS_MIL-VT.py", line 78, in main
model = MIL_VT_FineTune(base_model, MODEL_PATH_finetune, num_classes=n_classes)
File "/workspace/test/MIL-VT-main/models/FinetuneVTmodels.py", line 28, in MIL_VT_FineTune
model = create_model(model_name=base_model,
File "/opt/conda/envs/dual_learning/lib/python3.8/site-packages/timm/models/factory.py", line 71, in create_model
model = create_fn(pretrained=pretrained, pretrained_cfg=pretrained_cfg, **kwargs)
File "/workspace/test/MIL-VT-main/models/MIL_VT.py", line 216, in MIL_VT_small_patch16_512
model = MILVisionTransformer(
File "/workspace/test/MIL-VT-main/models/MIL_VT.py", line 13, in init
super().init(*args, **kwargs)
TypeError: init() got an unexpected keyword argument 'pretrained_cfg'

**Comment by jumpjet668** [comment]
@liqiangde 
你好，请问问题解决了吗？我现在也有这个问题。

问题刚刚解决了，是timm版本的问题，timm新版本不支持torch._six，在helpers.py文件中把 from torch._six import container_abcs 改为 import collections.abc as container_abcs问题解决

**Comment by YXtrees** [comment]
> 是的，在添加我上面提到的代码后，我已经成功运行了它，没有错误。在此之前，我遇到了和你一样的问题。

请问您添加的是什么代码，添加到那个地方

**Comment by YXtrees** [comment]
> from models.MIL_VT import *
> 
> try add above code to train_APTOS_MIL-VT.py

请问您用的几张卡跑通的代码

**Comment by YXtrees** [comment]
一直出现这个问题，怎解决
Traceback (most recent call last):
  File "train_APTOS_MIL-VT.py", line 421, in <module>
    main()
  File "train_APTOS_MIL-VT.py", line 189, in main
    train(epoch, model, criterion, optimizer, train_loader, max_epoch, tbWriter)
  File "train_APTOS_MIL-VT.py", line 252, in train
    outputs_class, outputs_MIL = model(inputs)
  File "/usr/local/miniconda3/envs/milvt/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/miniconda3/envs/milvt/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 160, in forward
    replicas = self.replicate(self.module, self.device_ids[:len(inputs)])
  File "/usr/local/miniconda3/envs/milvt/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 165, in replicate
    return replicate(module, device_ids, not torch.is_grad_enabled())
  File "/usr/local/miniconda3/envs/milvt/lib/python3.8/site-packages/torch/nn/parallel/replicate.py", line 88, in replicate
    param_copies = _broadcast_coalesced_reshape(params, devices, detach)
  File "/usr/local/miniconda3/envs/milvt/lib/python3.8/site-packages/torch/nn/parallel/replicate.py", line 71, in _broadcast_coalesced_reshape
    tensor_copies = Broadcast.apply(devices, *tensors)
  File "/usr/local/miniconda3/envs/milvt/lib/python3.8/site-packages/torch/nn/parallel/_functions.py", line 22, in forward
    outputs = comm.broadcast_coalesced(inputs, ctx.target_gpus)
  File "/usr/local/miniconda3/envs/milvt/lib/python3.8/site-packages/torch/nn/parallel/comm.py", line 56, in broadcast_coalesced
    return torch._C._broadcast_coalesced(tensors, devices, buffer_size)
RuntimeError: CUDA error: no kernel image is available for execution on the device
